services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: training
      POSTGRES_USER: vusi
      POSTGRES_PASSWORD: password
    volumes:
     - ./src/test/resources/data/northwind.sql:/docker-entrypoint-initdb.d/northwind.sql
